info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
grails:
  mongodb:
    url: mongodb+srv://admin:1234@cluster0.dwstifj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  codegen:
    defaultPackage: org.udl
  profile: web

  plugin:
    springsecurity:
      successHandler:
        auth:
          loginFormUrl: '/auth/auth'
          postOnly: true
      controllerAnnotations:
        staticRules:
          - pattern: '/'
            access: [ 'permitAll' ]
          - pattern: '/home/index'
            access: [ 'permitAll' ]
          - pattern: '/auth/index'
            access: [ 'permitAll' ]
          - pattern: '/auth/auth'
            access: [ 'permitAll' ]
          - pattern: '/login/authenticate'
            access: [ 'permitAll' ]
          - pattern: '/auth/create'
            access: [ 'permitAll' ]
          - pattern: '/auth/save'
            access: [ 'permitAll' ]
          - pattern: '/assets/**'
            access: [ 'permitAll' ]
          - pattern: '/**/js/**'
            access: [ 'permitAll' ]
          - pattern: '/**/css/**'
            access: [ 'permitAll' ]
          - pattern: '/**/images/**'
            access: [ 'permitAll' ]
          - pattern: '/calendar/**'
            access: [ 'permitAll' ]
          - pattern: '/event/**'
            access: [ 'permitAll' ]